"""add_matching_queue_and_matches_tables

Revision ID: 0e9403cb1b73
Revises: 78a23a00270e
Create Date: 2026-07-17 20:33:25.368173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9403cb1b73'
down_revision: Union[str, None] = '78a23a00270e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matching_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_queue_status'), 'matching_queue', ['status'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('degree_eligible', sa.Boolean(), nullable=False),
    sa.Column('language_eligible', sa.Boolean(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('research_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explanation_status', sa.String(), nullable=False),
    sa.Column('explanation_claimed_by', sa.String(), nullable=True),
    sa.Column('explanation_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_url'], ['jobs.url'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_url', name='uq_candidate_job_match')
    )
    op.create_index(op.f('ix_matches_candidate_id'), 'matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_matches_explanation_status'), 'matches', ['explanation_status'], unique=False)
    op.create_index(op.f('ix_matches_job_url'), 'matches', ['job_url'], unique=False)
    op.add_column('candidate_profiles', sa.Column('skill_embedding', sa.Text(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('research_embedding', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('skill_embedding', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('research_embedding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'research_embedding')
    op.drop_column('jobs', 'skill_embedding')
    op.drop_column('candidate_profiles', 'research_embedding')
    op.drop_column('candidate_profiles', 'skill_embedding')
    op.drop_index(op.f('ix_matches_job_url'), table_name='matches')
    op.drop_index(op.f('ix_matches_explanation_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_candidate_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_matching_queue_status'), table_name='matching_queue')
    op.drop_table('matching_queue')
    # ### end Alembic commands ###
