"""split_job_orchestrations

Revision ID: 5ef19a5d430a
Revises: 8db1e8a2a07c
Create Date: 2026-07-18 16:16:51.120113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef19a5d430a'
down_revision: Union[str, None] = '8db1e8a2a07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler_checkpoints',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_successful_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('job_orchestrations',
    sa.Column('job_url', sa.String(), nullable=False),
    sa.Column('detection_status', sa.String(), nullable=False),
    sa.Column('detection_claimed_by', sa.String(), nullable=True),
    sa.Column('detection_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('translation_status', sa.String(), nullable=False),
    sa.Column('translation_claimed_by', sa.String(), nullable=True),
    sa.Column('translation_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('refinement_status', sa.String(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_url'], ['jobs.url'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_url')
    )
    op.create_index(op.f('ix_job_orchestrations_detection_status'), 'job_orchestrations', ['detection_status'], unique=False)
    op.create_index(op.f('ix_job_orchestrations_job_url'), 'job_orchestrations', ['job_url'], unique=False)
    op.create_index(op.f('ix_job_orchestrations_refinement_status'), 'job_orchestrations', ['refinement_status'], unique=False)
    op.create_index(op.f('ix_job_orchestrations_translation_status'), 'job_orchestrations', ['translation_status'], unique=False)
    op.drop_index(op.f('ix_jobs_detection_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_refinement_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_translation_status'), table_name='jobs')
    op.drop_column('jobs', 'claimed_by')
    op.drop_column('jobs', 'claimed_at')
    op.drop_column('jobs', 'detection_claimed_at')
    op.drop_column('jobs', 'detection_status')
    op.drop_column('jobs', 'detection_claimed_by')
    op.drop_column('jobs', 'translation_claimed_by')
    op.drop_column('jobs', 'translation_status')
    op.drop_column('jobs', 'translation_claimed_at')
    op.drop_column('jobs', 'refinement_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('refinement_status', sa.VARCHAR(), nullable=False))
    op.add_column('jobs', sa.Column('translation_claimed_at', sa.DATETIME(), nullable=True))
    op.add_column('jobs', sa.Column('translation_status', sa.VARCHAR(), nullable=False))
    op.add_column('jobs', sa.Column('translation_claimed_by', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('detection_claimed_by', sa.VARCHAR(), nullable=True))
    op.add_column('jobs', sa.Column('detection_status', sa.VARCHAR(), nullable=False))
    op.add_column('jobs', sa.Column('detection_claimed_at', sa.DATETIME(), nullable=True))
    op.add_column('jobs', sa.Column('claimed_at', sa.DATETIME(), nullable=True))
    op.add_column('jobs', sa.Column('claimed_by', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_jobs_translation_status'), 'jobs', ['translation_status'], unique=False)
    op.create_index(op.f('ix_jobs_refinement_status'), 'jobs', ['refinement_status'], unique=False)
    op.create_index(op.f('ix_jobs_detection_status'), 'jobs', ['detection_status'], unique=False)
    op.drop_index(op.f('ix_job_orchestrations_translation_status'), table_name='job_orchestrations')
    op.drop_index(op.f('ix_job_orchestrations_refinement_status'), table_name='job_orchestrations')
    op.drop_index(op.f('ix_job_orchestrations_job_url'), table_name='job_orchestrations')
    op.drop_index(op.f('ix_job_orchestrations_detection_status'), table_name='job_orchestrations')
    op.drop_table('job_orchestrations')
    op.drop_table('crawler_checkpoints')
    # ### end Alembic commands ###
