"""initial schema

Revision ID: 7a5692b0b260
Revises: None
Create Date: 2026-07-17 07:27:20.706604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5692b0b260'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('requirements_en', sa.Text(), nullable=True),
    sa.Column('detection_status', sa.String(), nullable=False),
    sa.Column('detection_claimed_by', sa.String(), nullable=True),
    sa.Column('detection_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('translation_status', sa.String(), nullable=False),
    sa.Column('translation_claimed_by', sa.String(), nullable=True),
    sa.Column('translation_claimed_at', sa.DateTime(), nullable=True),
    sa.Column('refinement_status', sa.String(), nullable=False),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_detection_status'), 'jobs', ['detection_status'], unique=False)
    op.create_index(op.f('ix_jobs_refinement_status'), 'jobs', ['refinement_status'], unique=False)
    op.create_index(op.f('ix_jobs_translation_status'), 'jobs', ['translation_status'], unique=False)
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_translation_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_refinement_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_detection_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
