"""remove experience from cv

Revision ID: 7b8fbc85ee1d
Revises: fd3646783aff
Create Date: 2026-08-03 21:25:22.275769

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b8fbc85ee1d"
down_revision: Union[str, None] = "fd3646783aff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.drop_column("experience")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("experience", sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
