"""add_language_and_translation_to_profiles

Revision ID: 8de6e55899ef
Revises: 5ef19a5d430a
Create Date: 2026-07-19 11:41:32.116769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de6e55899ef'
down_revision: Union[str, None] = '5ef19a5d430a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('language_code', sa.String(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('raw_text_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'raw_text_en')
    op.drop_column('candidate_profiles', 'language_code')
    # ### end Alembic commands ###
