"""initial_schema

Revision ID: 9c56d4fb1329
Revises: None
Create Date: 2026-08-06 16:51:27.337263

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c56d4fb1329"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("cv_file_path", sa.String(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("language_code", sa.String(), nullable=True),
        sa.Column("raw_text_en", sa.Text(), nullable=True),
        sa.Column("highest_degree", sa.String(), nullable=True),
        sa.Column("degree_fields", sa.Text(), nullable=True),
        sa.Column("skills", sa.Text(), nullable=True),
        sa.Column("languages", sa.Text(), nullable=True),
        sa.Column("preferred_locations", sa.Text(), nullable=True),
        sa.Column("research_interests", sa.Text(), nullable=True),
        sa.Column("skill_embedding", sa.Text(), nullable=True),
        sa.Column("research_embedding", sa.Text(), nullable=True),
        sa.Column("degree_embedding", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("status_message", sa.String(), nullable=True),
        sa.Column("claimed_by", sa.String(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("telegram_chat_id", sa.String(), nullable=True),
        sa.Column("is_notified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidate_profiles_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_candidate_profiles_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_candidate_profiles_telegram_chat_id"), ["telegram_chat_id"], unique=False
        )

    op.create_table(
        "crawler_checkpoints",
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("last_successful_url", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("deadline", sa.String(), nullable=True),
        sa.Column("employer", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("required_skills", sa.Text(), nullable=True),
        sa.Column("research_interests", sa.Text(), nullable=True),
        sa.Column("education_level", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("language_code", sa.String(), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("requirements_en", sa.Text(), nullable=True),
        sa.Column("skill_embedding", sa.Text(), nullable=True),
        sa.Column("research_embedding", sa.Text(), nullable=True),
        sa.Column("degree_embedding", sa.Text(), nullable=True),
        sa.Column("degree_fields", sa.Text(), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_url"), ["url"], unique=True)

    op.create_table(
        "matching_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("claimed_by", sa.String(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("matching_queue", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_matching_queue_status"), ["status"], unique=False)

    op.create_table(
        "job_orchestrations",
        sa.Column("job_url", sa.String(), nullable=False),
        sa.Column("detection_status", sa.String(), nullable=False),
        sa.Column("detection_claimed_by", sa.String(), nullable=True),
        sa.Column("detection_claimed_at", sa.DateTime(), nullable=True),
        sa.Column("translation_status", sa.String(), nullable=False),
        sa.Column("translation_claimed_by", sa.String(), nullable=True),
        sa.Column("translation_claimed_at", sa.DateTime(), nullable=True),
        sa.Column("refinement_status", sa.String(), nullable=False),
        sa.Column("claimed_by", sa.String(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(), nullable=True),
        sa.Column("embedding_status", sa.String(), nullable=False),
        sa.Column("embedding_claimed_by", sa.String(), nullable=True),
        sa.Column("embedding_claimed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["job_url"], ["jobs.url"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_url"),
    )
    with op.batch_alter_table("job_orchestrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_orchestrations_detection_status"), ["detection_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_orchestrations_embedding_status"), ["embedding_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_orchestrations_refinement_status"),
            ["refinement_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_job_orchestrations_translation_status"),
            ["translation_status"],
            unique=False,
        )

    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("job_url", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("degree_eligible", sa.Boolean(), nullable=False),
        sa.Column("language_eligible", sa.Boolean(), nullable=False),
        sa.Column("skill_score", sa.Float(), nullable=False),
        sa.Column("research_score", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("explanation_status", sa.String(), nullable=False),
        sa.Column("explanation_claimed_by", sa.String(), nullable=True),
        sa.Column("explanation_claimed_at", sa.DateTime(), nullable=True),
        sa.Column("telegram_notified", sa.Boolean(), nullable=False),
        sa.Column("telegram_notified_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_url"], ["jobs.url"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "job_url", name="uq_candidate_job_match"),
    )
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_matches_candidate_id"), ["candidate_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_matches_explanation_status"), ["explanation_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_matches_job_url"), ["job_url"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_matches_telegram_notified"), ["telegram_notified"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_matches_telegram_notified"))
        batch_op.drop_index(batch_op.f("ix_matches_job_url"))
        batch_op.drop_index(batch_op.f("ix_matches_explanation_status"))
        batch_op.drop_index(batch_op.f("ix_matches_candidate_id"))

    op.drop_table("matches")
    with op.batch_alter_table("job_orchestrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_orchestrations_translation_status"))
        batch_op.drop_index(batch_op.f("ix_job_orchestrations_refinement_status"))
        batch_op.drop_index(batch_op.f("ix_job_orchestrations_embedding_status"))
        batch_op.drop_index(batch_op.f("ix_job_orchestrations_detection_status"))

    op.drop_table("job_orchestrations")
    with op.batch_alter_table("matching_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_matching_queue_status"))

    op.drop_table("matching_queue")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_url"))

    op.drop_table("jobs")
    op.drop_table("crawler_checkpoints")
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_telegram_chat_id"))
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_status"))
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_email"))

    op.drop_table("candidate_profiles")
    # ### end Alembic commands ###
