"""add_telegram_notified_to_matches

Revision ID: f50087972584
Revises: 9a8f7e6d5c4b
Create Date: 2026-07-31 21:19:33.668449

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f50087972584"
down_revision: Union[str, None] = "9a8f7e6d5c4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_profiles_telegram_chat_id"), ["telegram_chat_id"], unique=False
        )

    with op.batch_alter_table("crawler_checkpoints", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("job_orchestrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_orchestrations_job_url"))

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "first_seen",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "last_seen",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "telegram_notified", sa.Boolean(), nullable=False, server_default=sa.text("0")
            )
        )
        batch_op.add_column(sa.Column("telegram_notified_at", sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_matches_telegram_notified"), ["telegram_notified"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_matches_telegram_notified"))
        batch_op.drop_column("telegram_notified_at")
        batch_op.drop_column("telegram_notified")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "last_seen",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.alter_column(
            "first_seen",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("job_orchestrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_orchestrations_job_url"), ["job_url"], unique=False
        )

    with op.batch_alter_table("crawler_checkpoints", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_telegram_chat_id"))

    # ### end Alembic commands ###
